title: "Martin Janiczek"
author: "Martin Janiczek"
description: ""

bluesky_username: "janiczek.cz"
github_username: "janiczek"

remote_theme: pages-themes/primer@v0.6.0

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Posts

